### ISSUE TITLE
step_by_step/controller.rb:7:in `private_class_method': undefined method `rollout?' for class `Class' (NameError)

### ISSUE THREAD

**Issue by tanwcw** [cobalthq/step_by_step#4]
Got this error with `step_by_step` 0.0.1.7. Came up when trying to run `rails server`.

```
/Users/williamtan/web-app/.bundle/gems/step_by_step-0.0.1.7/lib/step_by_step/controller.rb:7:in `private_class_method': undefined method `rollout?' for class `Class' (NameError)
	from /Users/williamtan/web-app/.bundle/gems/step_by_step-0.0.1.7/lib/step_by_step/controller.rb:7:in `block in <module:Controller>'
	from /Users/williamtan/web-app/.bundle/gems/activesupport-4.2.7.1/lib/active_support/concern.rb:120:in `class_eval'
	from /Users/williamtan/web-app/.bundle/gems/activesupport-4.2.7.1/lib/active_support/concern.rb:120:in `append_features'
	from /Users/williamtan/web-app/.bundle/gems/step_by_step-0.0.1.7/lib/step_by_step.rb:10:in `include'
	from /Users/williamtan/web-app/.bundle/gems/step_by_step-0.0.1.7/lib/step_by_step.rb:10:in `block in <class:Engine>'
	from /Users/williamtan/web-app/.bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/williamtan/web-app/.bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
	from /Users/williamtan/web-app/.bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/williamtan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/williamtan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/williamtan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/williamtan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/williamtan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/williamtan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/williamtan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/williamtan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/williamtan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/williamtan/web-app/.bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/williamtan/web-app/.bundle/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
	from /Users/williamtan/web-app/config/environment.rb:5:in `<top (required)>'
	from /Users/williamtan/web-app/spec/rails_helper.rb:5:in `require'
	from /Users/williamtan/web-app/spec/rails_helper.rb:5:in `<top (required)>'
	from /Users/williamtan/web-app/spec/features/registrations_spec.rb:1:in `require'
	from /Users/williamtan/web-app/spec/features/registrations_spec.rb:1:in `<top (required)>'
	from /Users/williamtan/web-app/.bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
	from /Users/williamtan/web-app/.bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /Users/williamtan/web-app/.bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from /Users/williamtan/web-app/.bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /Users/williamtan/web-app/.bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from /Users/williamtan/web-app/.bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /Users/williamtan/web-app/.bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /Users/williamtan/web-app/.bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/williamtan/web-app/.bundle/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
	from /Users/williamtan/.rvm/gems/ruby-2.2.3@web-app/bin/rspec:23:in `load'
	from /Users/williamtan/.rvm/gems/ruby-2.2.3@web-app/bin/rspec:23:in `<main>'
	from /Users/williamtan/.rvm/gems/ruby-2.2.3@web-app/bin/ruby_executable_hooks:15:in `eval'
	from /Users/williamtan/.rvm/gems/ruby-2.2.3@web-app/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by chrhansen** [comment]
At @tanwcw short term you can downgrade to version 0.0.1.6 in Rails 4, and long term submit a pull-request that fixes it my screwup here: https://github.com/cobalthq/step_by_step/commit/16c036568af464c5efb00da5cb38d2c06298c5e4

Basically figure out what to use instead of `hide_action` in Rails 5. `private_class_method` was obviously not the right thing.

**Comment by tanwcw** [comment]
@chrhansen Yup did that! In the meanwhile should we update our gemfile to use 0.0.1.6 first?

**Comment by chrhansen** [comment]
@tanwcw I guess so. Because, 0.0.1.6 only gives a warning whereas 0.0.1.7, crashes, right?

**Comment by tanwcw** [comment]
@chrhansen Don't see any warnings on 0.0.1.6, but 0.0.1.7 crashes as you say.

**Comment by chrhansen** [comment]
Ok. It might only trigger warnings when the gem is actually used.

**Comment by msx2** [comment]
@chrhansen I've actually edited your comment and removed Trello link. This is a public repository, so anyone has access to its content and we shouldn't leak any information 😉

**Comment by chrhansen** [comment]
@msx2 Oh thanks! Didn't see we had moved into the public repo :)

**Comment by msx2** [comment]
@chrhansen This has always been a public repository as it's a gem published on [RubyGems.org](https://rubygems.org/gems/step_by_step) 😉

**Comment by msx2** [comment]
@tanwcw @chrhansen There is a `0.0.1.8` version of the gem now that should fix this issue, and also the deprecation warnings.
